name: Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version  # Verify installation

      # Step 4: Run Tests
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

      # Step 5: Run Linter
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"
